### ISSUE TITLE
Travis deploy provider "script" should support sequences (gives weird error if you try)

### ISSUE THREAD

**Issue by beamerblvd** [travis-ci/travis-yml#92] opened 2019-01-20 17:12 UTC
I need to do this in order to deploy with Maven:

```yaml
...
      deploy:
        - provider: script
          script:
            - openssl aes-256-cbc -K $encrypted_dc2adf587a89_key -iv $encrypted_dc2adf587a89_iv -in .travis.gpg.enc -out .travis.gpg -d
            - openssl aes-256-cbc -K $encrypted_dc2adf587a89_key -iv $encrypted_dc2adf587a89_iv -in .travis.settings.xml.enc -out .travis.settings.xml -d
            - gpg --import .travis.gpg
            - cp .travis.settings.xml $HOME/.m2/settings.xml
            - mvn clean deploy -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -P sign -B -V -e
...
```

The worst bit is that, if you try this, you get a very strange error that doesn't actually indicate what you've done wrong:

```
Installing deploy dependencies
Successfully installed dpl-script-1.10.6
Parsing documentation for dpl-script-1.10.6
Installing ri documentation for dpl-script-1.10.6
Done installing documentation for dpl-script after 0 seconds
1 gem installed
/home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/cli.rb:54:in `system': wrong first argument (ArgumentError)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/cli.rb:54:in `shell'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-script-1.10.6/lib/dpl/provider/script.rb:19:in `push_app'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/provider.rb:199:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/provider.rb:199:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.6/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
```

I figured it out by browsing through the `travis-ci/travis-yml` source code and finding [this](https://github.com/travis-ci/travis-yml/blob/master/lib/travis/yaml/spec/def/deploy/script.rb#L6-L12):

```ruby
...
          class Script < Deploy
            register :script

            def define
              super
              map :script, to: :str # TODO should be a seq?
            end
...
```

`# TODO should be a seq?` ... Yes, it should definitely be a sequence. Particularly important here, the top-level `script` directive supports sequences, so this directive's not supporting sequences, with no documentation saying it doesn't, and with a weird error message that doesn't indicate the problem, is a bug.

For now, I think I can get around it with this (I'm about to test it), but this is not the correct way to do this, especially since I'm using multiple providers, and `before_deploy` runs before each provider (unnecessary here).

```yaml
...
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_dc2adf587a89_key -iv $encrypted_dc2adf587a89_iv -in .travis.gpg.enc -out .travis.gpg -d
        - openssl aes-256-cbc -K $encrypted_dc2adf587a89_key -iv $encrypted_dc2adf587a89_iv -in .travis.settings.xml.enc -out .travis.settings.xml -d
        - gpg --import .travis.gpg
        - cp .travis.settings.xml $HOME/.m2/settings.xml
      deploy:
        - provider: script
          script: "mvn clean deploy -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -P sign -B -V -e"
...
```

**Comment by BanzaiMan** [comment] 2019-01-21 15:03
Hello, there. Thanks for taking time to open this issue. However, this is a repository for _specifying_ the YAML schema, not adding features to what should or should not be accepted as valid.

So, I'm closing this as a duplicate of https://github.com/travis-ci/dpl/issues/673.

**Closed by BanzaiMan** 2019-01-21 15:03 UTC

**Comment by beamerblvd** [comment] 2019-01-21 16:49
Thanks or pointing that out to me, but I disagree that that means this needs to be closed. There needs to be an issue in _both_ repositories: travis-ci/dpl#673 for the work that needs to be done there and this issue for the work that needs to be done here. That way, the work that needs to be done here won't be easily overlooked.
